### PR TITLE
Use sysconf to get the total online CPUs

### PR DESCRIPTION
**Pull request by janaknat**
num_cpus does not return the total number of CPUs if aperf is taskset. Use sysconf to get the total number of online CPUs.

[compare.tar.gz](https://github.com/aws/aperf/files/15505630/compare.tar.gz)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by wash-amzn** [comment]
Do you have a reproducible example of this problem? I never ran into it.

**Comment by wash-amzn** [comment]
The bigger problem to solve here is the report of failures when the set of disabled CPUs isn't contiguous and at the end of the CPU list.

**Comment by janaknat** [comment]
> Do you have a reproducible example of this problem? I never ran into it.

Run aperf with taskset. Ex: `taskset 1 ./aperf record`. The perf stat values are limited to only one CPU.

**Comment by wash-amzn** [comment]
> > Do you have a reproducible example of this problem? I never ran into it.
> 
> Run aperf with taskset. Ex: `taskset 1 ./aperf record`. The perf stat values are limited to only one CPU.

That is not my experience. I was doing many runs with taskset and aperf recorded all CPUs normally.

**Review by wash-amzn — APPROVED** [review]

**Pull request merged**
